services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=alejcartoon1333@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  soat-peru:
    image: soat-peru
    build:
      context: ../soat-peru
    restart: always
    expose:
      - '3000'
    environment:
      - VIRTUAL_HOST=segurovirtual-pe.com
      - LETSENCRYPT_HOST=segurovirtual-pe.com
      - VIRTUAL_PORT=3000  # Nuxt server
      - SOCKET_URL=https://server-sockets.segurovirtual-pe.com

  server-sockets-peru:
    image: server-sockets-peru
    build:
      context: ../server-sockets-peru
    restart: always
    expose:
      - '3001'
    environment:
      - VIRTUAL_HOST=server-sockets.segurovirtual-pe.com
      - LETSENCRYPT_HOST=server-sockets.segurovirtual-pe.com
      - SOCKET_PORT=3001
      - SOCKET_HOST=0.0.0.0
      - CLIENT_URL=https://segurovirtual-pe.com
volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
